alias workspace="cd ${GITPOD_REPO_ROOT}"
alias webui="gp preview $(gp url 8080)"
alias temporal="/workspace/bin/temporal"
alias tctl="/workspace/bin/tctl"
alias ex1="cd ${GITPOD_REPO_ROOT}/exercises/codec-server/practice"
alias ex2="cd ${GITPOD_REPO_ROOT}/exercises/custom-converter/practice"
alias ex3="cd ${GITPOD_REPO_ROOT}/exercises/codec-server/solution"
alias ex4="cd ${GITPOD_REPO_ROOT}/exercises/codec-server/solution"
echo "Your workspace is located at: ${GITPOD_REPO_ROOT}"
echo "Type the command     workspace      to return to the workspace directory at any time."
